# Generated by Django 5.0 on 2023-12-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0003_alter_evento_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
